#ifndef STM32G4_INSTANCE_H
	#define STM32G4_INSTANCE_H

#include "stm32g4_register.h"

typedef volatile struct
{
	RCC_CR_reg CR;
	RCC_ICSCR_reg ICSCR;
	RCC_CFGR_reg CFGR;
	RCC_PLLCFGR_reg PLLCFGR;
	uint32_t RESERVED0;
	uint32_t RESERVED1;
	RCC_CIER_reg CIER;
	RCC_CIFR_reg CIFR;
	RCC_CICR_reg CICR;
	uint32_t RESERVED2;
	RCC_AHB1RSTR_reg AHB1RSTR;
	RCC_AHB2RSTR_reg AHB2RSTR;
	RCC_AHB3RSTR_reg AHB3RSTR;
	uint32_t RESERVED3;
	RCC_APB1RSTR1_reg APB1RSTR1;
	RCC_APB1RSTR2_reg APB1RSTR2;
	RCC_APB2RSTR_reg APB2RSTR;
	uint32_t RESERVED4;
	RCC_AHB1ENR_reg AHB1ENR;
	RCC_AHB2ENR_reg AHB2ENR;
	RCC_AHB3ENR_reg AHB3ENR;
	uint32_t RESERVED5;
	RCC_APB1ENR1_reg APB1ENR1;
	RCC_APB1ENR2_reg APB1ENR2;
	RCC_APB2ENR_reg APB2ENR;
	uint32_t RESERVED6;
	RCC_AHB1SMENR_reg AHB1SMENR;
	RCC_AHB2SMENR_reg AHB2SMENR;
	RCC_AHB3SMENR_reg AHB3SMENR;
	uint32_t RESERVED7;
	RCC_APB1SMENR1_reg APB1SMENR1;
	RCC_APB1SMENR2_reg APB1SMENR2;
	RCC_APB2SMENR_reg APB2SMENR;
	uint32_t RESERVED8;
	RCC_CCIPR_reg CCIPR;
	uint32_t RESERVED9;
	RCC_BDCR_reg BDCR;
	RCC_CSR_reg CSR;
	RCC_CRRCR_reg CRRCR;
	RCC_CCIPR2_reg CCIPR2;
} RCC_BitField_TypeDef;

typedef volatile struct {
	GPIO_MODER_reg MODER;
	GPIO_OTYPER_reg OTYPER;
	GPIO_OSPEEDR_reg OSPEEDR;
	GPIO_PUPDR_reg PUPDR;
	GPIO_IDR_reg IDR;
	GPIO_ODR_reg ODR;
	uint32_t BSRR;
	GPIO_LCKR_reg LCKR;
	GPIO_AFR_reg AFR;
	uint32_t BRR;
} GPIO_BitField_TypeDef;

typedef volatile struct
{
    I2C_CR1_reg CR1;
    I2C_CR2_reg CR2;
    I2C_OAR1_reg OAR1;
    I2C_OAR2_reg OAR2;
    I2C_TIMINGR_reg TIMINGR;
    I2C_TIMEOUTR_reg TIMEOUTR;
    I2C_ISR_reg ISR;
    I2C_ICR_reg ICR;
    I2C_PECR_reg PECR;
    I2C_RXDR_reg RXDR;
    I2C_TXDR_reg TXDR;
} I2C_BitField_TypeDef;

#endif

/*** EOF ***/
